server:
  port: 9000
spring:
  jpa:
    #generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/locationservice
    username: postgres
    password: root
  flyway:
    enabled: true
